### ISSUE TITLE
What's the plan for CalDav support?

### ISSUE THREAD

**Issue by Julian4711** [alainm23/planify#1049]
Hi, sorry, this may be a dumb question but: Is support for CalDav already implemented?
I tried the recent flatpack as well as the recent beta version and both do not seem to have that feature.
Still people are mentioning it in other issues on this board. Am I just too blind to find it? thanks

**Comment by Coshibu** [comment]
I second this. Syncing the whole thing via CalDav or another self-hosted solution is painfully missing.

**Comment by kierkegaardian** [comment]
It's there in my version, it just doesn't fully work.

**Comment by Julian4711** [comment]
So it was there in older versions and now it's removed? Hope very much it returns.

**Comment by shvchk** [comment]
It's under development https://github.com/alainm23/planify/issues/993#issuecomment-1610094903
Waiting for it, too 🙏

**Comment by bepolymathe** [comment]
I hope this too

**Comment by ekasprzak** [comment]
Seems like mentioned above #993 was closed as completed half a year ago, does it mean there is no plan to implement CalDav/NextCloud support?

**Comment by alainm23** [comment]
Hi guys, after a couple of months with personal problems, I can finally get back to Planify development actively.

Regarding CalDAV support, it is true that it was initially available but for technical reasons I decided not to include it in Planify 4+, using Evolution Data Server is very cumbersome and has little documentation and it is not possible to handle it as I like or at least as Planify architecture works.

As a solution I plan to create my own CalDAV sync service (I have done some research on this and I think it is possible) which would considerably improve memory usage and would be more in line with how Planify works. 

I can't give you an estimated date for CalDAV support (I'm the only one working on this project, I have another job and a family to support) but I hope to be able to tell you the progress little by little.

Thank you.

**Comment by bepolymathe** [comment]
Thanks for reply and perspectives. 
And why not build on DavX5 rather than start from scratch?

**Comment by Nico7as** [comment]
Hi @alainm23 
Some apps don't rely on EDS, like Thunderbird if I'm not mistaken.

I personally really appreciate when an app connects to EDS. I get the feeling of a mature GNOME ecosystem.
I use NextCloud, with GNOME Online Accounts. 

But I'm no developer so Ii'll trust you if you say that's not a proper fit for Planify.

I hope it'll land soon, so I can continue my everlasting quest for the best task manager for GNOME...

**Comment by shvchk** [comment]
@Nico7as also, some people don't use GNOME 😉

**Comment by janvlug** [comment]
> EDS

I had to look this up: [Evolution Data Server](https://wiki.gnome.org/Apps/Evolution/EDS_Architecture).

**Comment by alainm23** [comment]
Hi guys, thanks for your trust and keep using Planify. after v4.4 and Board View support, the next big way is CalDAV support. I have been investigating about this and I have a progress, at the moment I can login and see all the task lists of an account in Nextcloud, I can't say it has been simple because CalDAV works on XML and it's the first time I use it, also it cost me to find an XML library for Vala, at the end I opted for [gxml](https://github.com/GNOME/gxml) from @esodan  (Thanks!!!!), I will keep you informed about the progress and later I will show some screenshots.

**Comment by esodan** [comment]
> Hi guys, thanks for your trust and keep using Planify. after v4.4 and Board View support, the next big way is CalDAV support. I have been investigating about this and I have a progress, at the moment I can login and see all the task lists of an account in Nextcloud, I can't say it has been simple because CalDAV works on XML and it's the first time I use it, also it cost me to find an XML library for Vala, at the end I opted for [gxml](https://github.com/GNOME/gxml) from @esodan (Thanks!!!!), I will keep you informed about the progress and later I will show some screenshots.

If you need help on how create classes that read the XML, by deriving your object from XML.Element and use the nick for automatic bind your properties to XML properties and nodes, I can help you. Thanks for using GXml

**Comment by esodan** [comment]
> Hi guys, thanks for your trust and keep using Planify. after v4.4 and Board View support, the next big way is CalDAV support. I have been investigating about this and I have a progress, at the moment I can login and see all the task lists of an account in Nextcloud, I can't say it has been simple because CalDAV works on XML and it's the first time I use it, also it cost me to find an XML library for Vala, at the end I opted for [gxml](https://github.com/GNOME/gxml) from @esodan (Thanks!!!!), I will keep you informed about the progress and later I will show some screenshots.

Also if you need a standard API for Data Base access you can check out VDA at https://gitlab.gnome.org/esodan/libvda

**Comment by alainm23** [comment]
This is my first preview, I am using a Nextcloud account at https://use01.thegood.cloud/, at least with this instance it works correctly. I will probably have to do more tests with other providers, maybe it will change something. any other casuistry I should take into account?

[Grabación de pantalla desde 2024-01-11 18-38-22.webm](https://github.com/alainm23/planify/assets/33765137/9777d950-7b1f-444d-a26a-5ce30ef2e902)

**Comment by VictorVow** [comment]
It looks great, glad to see this feature finally landing. Hope to see support for generic CalDAV, as I intended to use Planify with a radicale or baikal server.

**Comment by zefr0x** [comment]
The right way doing the login process is to use app tokens. Like the official NextCloud desktop app, it will open a page in the web browser for you to login rather than doing it directly from the application.

The login process not always as simple as username+password, there might be an OTP or even a Hardware Key or other complex setup (NextCloud allow flexible configuration for the login process using plugins).

Also every application should have a unique password rather than just using the user's main password.

I don't know how exactly it was implemented in the NextCloud app, but I expect that there is an API that will allow you to open a login page in the browser then wait for a response with a secret token that could be saved in `org.freedesktop.secrets` and used as a normal password without worrying about any complex setup.

## Edited:
I found a reference here for `Login flow v2`: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2


It seems to work like I expected.

**Comment by zefr0x** [comment]
I want also to mention that people with self hosted Nextcloud server in there home might be using a self signed SSL certificate to use Nextcloud throw `https` rather than `http`.

By default it will give an error, Planify should make it clear in the UI that it failed to verify the legitimacy of the server's SSL certificate and therefore could not establish a secure connection to it.

I don't think that you should create a UI that shows the SSL certificate requesting a manual verification by the user (like the Nextcloud desktop app), this process should be system wide from the system settings. You should just show a clear error message.

**Comment by alainm23** [comment]
@Victor239 I just tried Radicale and there are a couple of changes to be made with respect to Nextcloud, mostly in the server URL, otherwise it works without problems.

**Comment by alainm23** [comment]
@zefr0x Interesting, Gnome only uses the server path, username and password, I would like to follow that path.

**Comment by alainm23** [comment]
@esodan Thanks, I have an [initial code](https://github.com/alainm23/planify/blob/develop/core/Services/CalDAV/CalDAV.vala#L282) with the documentation I have found, it works, but if it could be improved it would be great.

**Comment by wrenix** [comment]
Wow, is it possible to sync with Nextcloud-Desk eigther? I really like the kanbanboard and android app

**Comment by zefr0x** [comment]
> @zefr0x Interesting, Gnome only uses the server path, username and password, I would like to follow that path.


They have open issues in there issue tracker:
https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues/81
https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues/178
And there is a mention to it here:
https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues/184

There are no objections to this flow, as tags were added to `issue 81` three months ago.

**Comment by alainm23** [comment]
Hi guys, a devel version for CalDAV users is available. help me to debug it first.

https://github.com/alainm23/planify/issues/1118

**Comment by zefr0x** [comment]
For UX it would be better to have will-known services listed (even if they share the same API), rather than just a generic option for CalDAV. Since non-technical user will not open Wikipedia to read about CalDAV, he will just consider that the service is not supported.

It might be just some aliases before the generic CalDAV option. It should be easy in a modular code.

**Comment by alainm23** [comment]
Maybe Nextcloud?

**Comment by zefr0x** [comment]
> Maybe Nextcloud?

They might be:
- Nextcloud Calendar
- Tasks.org
- Google Calendar
- Apple iCloud Calendar
- Office 365
- Yahoo! Calendar
- *(Generic Option for CalDAV)*

**I'm not sure if those will work, but they support CalDAV as of my knowledge. (They should be researched and tested first)**

---

If the service has a centralized URL (e.g. Google Calendar), the user should not be asked for a URL.

Also if you don't feel comfortable with listing propriotary services, it might just be `Nextcloud` and `Tasks.org` for now.

**Comment by Nico7as** [comment]
> Wow, is it possible to sync with Nextcloud-Desk eigther? I really like the kanbanboard and android app

That'd be great !! 
NextCloud's Deck cards sometimes appears in tasks managers with specific title syntaxes ( List:Title etc...)
I'm no developer and I don't know Deck's inner workings or API, can't do it myself. but I'd gladly test it !

**Comment by symphorien** [comment]
Thank you for implementing caldav support. It seems to hardcode the url part of nextcloud: even if I type full url of my radicale instance (https://some.domain/username/uuid) then planify hits https://some.domain/username/uuid/remote.php/dav/ which is incorrect. Would it be possible to let people enter the URL?

**Comment by alainm23** [comment]
@symphorien At the moment we only support Nextcloud, we did not test using Radicale, if you have any user that I can borrow to test, I would be very grateful. Greetings.

**Comment by symphorien** [comment]
I sent you an email with credentials to the email of your github profile. Check your spam folder just in case :)

**Comment by ShinyDog2636** [comment]
What is the best way to get notified when generic CalDAV support is added to Planify? I use [Fastmail's](https://www.fastmail.help/hc/en-us/articles/1500000278342-Server-names-and-ports#calendar) CalDAV service.

I was super disappointed that updating from Planner to Planify removed CalDAV support but I am happy to see this feature is being worked on! Just a plug that Alain is taking donations on [Liberapay](https://liberapay.com/Alain/).  Thanks!

**Comment by pintert3** [comment]
How is this going? Looks like Radicale is still not supported. Anyway I can help?

**Comment by alainm23** [comment]
@pintert3  We have a new backend that will support Radicale among others, and it should be available tomorrow.
https://github.com/alainm23/planify/issues/1149

**Comment by pintert3** [comment]
Wow. That's absolutely fantastic. Thank you for your efforts @alainm23 .
