### ISSUE TITLE
Buttons disappear when resizing the window

### ISSUE THREAD

**Issue by wada3n** [alainm23/planify#1134]
When resizing the Planify app window, some buttons in the HeaderBar disappear and the "+" button to add a new task is hidden. 
This can be seen in the attached video.

[Screencast from 2024-02-15 19-23-49.webm](https://github.com/alainm23/planify/assets/13304792/a87fcfa9-e58a-41bb-9159-f70bee1259fe)

**Comment by Riksu9000** [comment]
One of the main reasons for this seems to be the task toolbar being too wide. Once a view that has a wide task has been opened, the GtkStack that contains the views takes on the size of the largest view, and so the clipping persists in other views. Setting the toolbar to invisible using inspector fixes clipping in this instance at least.

The biggest offender that's contributing to the random nature of this issue is the scheduling widget, which can have very different widths depending on the content. Perhaps it could be shrunk when there's not enough room.

![Screenshot from 2024-05-02 12-14-00](https://github.com/alainm23/planify/assets/37774658/9d4ef473-2d01-4eab-9fd5-2ff6a7d5adfc)

![Screenshot from 2024-05-02 12-14-15](https://github.com/alainm23/planify/assets/37774658/7512c550-9136-4ef3-968b-531bd9f30d06)

**Comment by alainm23** [comment]
[mobile.webm](https://github.com/alainm23/planify/assets/33765137/f53ee97c-6b1e-4be6-9796-01d72de0e760)

**Comment by Riksu9000** [comment]
I'm sorry, but it looks like this issue can still happen in some situations.

![Screenshot from 2024-05-09 12-50-55](https://github.com/alainm23/planify/assets/37774658/c01b8f9d-9d1a-4199-a623-056db484ec23)

![Screenshot from 2024-05-09 12-52-27](https://github.com/alainm23/planify/assets/37774658/9b8ef962-dd19-4e74-bd0a-b72a412e19d4)

**Comment by alainm23** [comment]
Thank you, I have already adjusted it

![image](https://github.com/alainm23/planify/assets/33765137/7a9dfa4d-5695-4f08-8f21-4de4eeb1392e)
![image](https://github.com/alainm23/planify/assets/33765137/ed2e607b-b351-476e-810c-b8662af0f94e)

**Comment by Riksu9000** [comment]
Thanks. Looks like it is working great now 👍
