### ISSUE TITLE
Constant cpu load

### ISSUE THREAD

**Issue by Jopp-gh** [alainm23/planify#1265]
**Describe the bug**
Planify is always one of the top processes in **gnome-system-monitor**, even in idle. 
Some components of Planify cause a load/burden (Linux Mint cinnamon 21.3).   
This constant load can be as much as a global 10% to 15% on my cpu. In the screenshot down below the loads is very low and not noticeable as a  load number, but nevertheless, Planify keeps staying *on the top*, no matter what happens. 

**To Reproduce**
1. Just open **gnome-system-monitor** or similar process monitor app and see Planify's constant load on the cpu. (My pc is a new build and oldest components are max 2yo) 

**Expected behavior**
Usually apps on Linux are quiet or pretty quiet - even more, if you don't use them. 

**Screenshots**
![Planify load_014305](https://github.com/alainm23/planify/assets/48620536/c1163c71-56d8-477b-941f-cf661a760f97)

**Desktop (please complete the following information):**
 - OS or DE: Mint cinnamon
 - Version 21.3 

**Additional context**
I've been using Planify for the past 3 months and monitored if updates didn't solve / mitigate this issue so far. Please look into this issue, bc you made a useful and good looking app.

**Comment by wisp3rwind** [comment]
For what it's worth, this seems to have improved for me in current versions, and CPU usage returns to 0% when the windows is not visible.

A while ago, I also profiled the application, and my conclusion was that at least part of the issue was due spinners that keep animating even when invisible as described in https://gitlab.gnome.org/GNOME/gtk/-/issues/1025. GTK merged a workaround for this somewhat common issue in https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7280, so this might be why things have improved.

In GNOME 47 (and thereby the latest libadwaita), [`AdwSpinner`](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.Spinner.html) [was added](https://release.gnome.org/47/developers/index.html) as a dedicated spinner widget with a new design. (And the animation is implemented in a different way. I'm not sure whether that further improves performance, but I have a hunch that it might: Profiling planify showed a lot of CPU usage due to CSS invalidation during the animation, and the new spinner does not use CSS.) So, if and when the runtime is updated to 47, it might be worth porting Planify to use these modern spinner widgets instead of the default GTK spinners. Looking at the linked MRs of the issue https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2616, it seems that would also have the potential to simplify UI definitions.

**Comment by wisp3rwind** [comment]
With https://github.com/alainm23/planify/commit/59a64fa629724a12d8c239087024d19b93d6774f (and before that the GTK changes), the issue as I observed it seems to be gone.

I'd suggest to close this, as well as #1333 and #1151, and have people open new issues should there be persisting performance problems.

**Comment by oktayacikalin** [comment]
I've closed mine (#1151) :+1:
