### ISSUE TITLE
Port to flatpak and on flathub

### ISSUE THREAD

**Issue by lsahn-gh** [alainm23/planify#13]
flatpak is one of the coolest tools for application-containerization. I had been working to port it to flatpak for a few days and I am just finished all the tasks.  
I'd take these jobs, porting to flatpak and put it on flathub, if you don't mind.  
Thank you for the cool app by the way.

**Comment by alainm23** [comment]
Thank you for support, I am interested FLATPACK but Planner still does not have any official release, this software has a bug and some things to improve, you could expect a little more please

**Comment by bilelmoussaoui** [comment]
If you need any help with Flatpak let me know.

**Comment by lsahn-gh** [comment]
@alainm23 What do you think of adding flatpak manifest into the top-level source tree?

If you put the manifest in the source tree, anyone can pull planner and develop it with gnome-builder as well as flatpak without the pain of installing dependencies. This is the way of GNOME developers using.

**Comment by lsahn-gh** [comment]
Feel free to test it and get me feedback :)

**Comment by alainm23** [comment]
@memnoth Thank you very much for the PR. I'm trying to build with this command: 
`flatpak-builder build-dir com.github.alainm23.planner.json`
And I get this error:
`Failed to init: Unable to find sdk org.gnome.Sdk version 3.30`
Possibly it's because I'm using elementary OS Juno

**Comment by lsahn-gh** [comment]
You need to install Sdk, Platform before run ``flatpak-builder``.

- flatpak install --user flathub org.gnome.Sdk//3.30
- flatpak install --user flathub org.gnome.Platform//3.30
- flatpak install --user flathub io.elementary.BaseApp//juno

Then try it again.

Or you can use ``gnome-builder`` which is IDE and has built-in flatpak commands that download all the required dependencies automatically except the ``BaseApp``. I always use the builder when I work on apps.
See this, https://flathub.org/apps/details/org.gnome.Builder

**Comment by lsahn-gh** [comment]
Also you can check out that whether you have required runtimes with ``flatpak list``.
You have to have those three runtimes to run planner.

**Comment by 4jNsY6fCVqZv** [comment]
While Flathub is certainly a good choice for the distribution of the app, I would like to point out that it is not an alternative for FLOSS users because Flathub does not offer a separate FLOSS platform. It contains proprietary services & apps. Maybe there will be an elementary OS Flatpak platform in the future. see https://github.com/orgs/elementary/projects/64
Then it would be wonderful if Planner 2 could be found there!

**Comment by alainm23** [comment]
Hello everyone, I am trying to package my Planner 2 with flatpak. Everything is fine but when I try to log in using Todoist, I get this error. Any ideas what happen? This only happens when building from flatpak.

![image](https://user-images.githubusercontent.com/33765137/72539417-43d6a880-384d-11ea-9122-3ff9b7baee49.png)
![image](https://user-images.githubusercontent.com/33765137/72539437-4c2ee380-384d-11ea-8910-c20f1c23edbf.png)
![image](https://user-images.githubusercontent.com/33765137/72539490-6072e080-384d-11ea-92fe-6795a52ce734.png)

```
(WebKitWebProcess:13): Gdk-ERROR **: 10:45:28.452: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 213 error_code 2 request_code 154 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by matfantinel** [comment]
Hi @alainm23 , I think that currently translations are not working either on Flatpak. Can you confirm?
I recently published two of my elementary apps to Flatpak and got the same issue. We can share info if one of us finds out more about it.

And sorry, I don't know how to help with your current issue logging in to Todoist right now :/

**Comment by bilelmoussaoui** [comment]
@matfantinel You need something along this in the main function before creating a new GtkApplication to setup i18n with gettext
```
    Intl.bindtextdomain (Config.GETTEXT_PACKAGE, Config.LOCALEDIR);
    Intl.bind_textdomain_codeset (Config.GETTEXT_PACKAGE, "UTF-8");
    Intl.textdomain (Config.GETTEXT_PACKAGE);
```
Otherwise, the i18n won't get detected correctly;

**Comment by alainm23** [comment]
@matfantinel check mi last commit: https://github.com/alainm23/planner/commit/47826d354c63ab16d3b8f7039f3254d98a503e72
