### ISSUE TITLE
Subtasks hidden when reopening app

### ISSUE THREAD

**Issue by yang-musa** [alainm23/planify#1428]
**Describe the bug**
I added a new task yesterday, and added many subtasks. At the end of the day I closed the app, and then I reopened it this morning. The project showed the correct number of tasks in the sidebar, but when I expanded the tasks no subtasks were visible. Subtasks remained hidden until I created a new dummy subtask - then the whole list showed.

**To Reproduce**
1. Open Planify
2. Create a new task under a project
3. Create subtasks under the new task
4. Close Planify
5. Reopen Planify
6. Search frantically for subtasks added previously....

**Expected behavior**
Expect all tasks created to be saved, and to be visible when the app is reopened.

**Screenshots**

**Desktop (please complete the following information):**
 - OS or DE: Fedora 40 Gnome, updated this morning
 - Version: Planify 4.11.0 installed from Flathub

**Additional context**
Thanks so much for a super app! Let me know if you need any additional info to figure out what's going on.

**Comment by alainm23** [comment]
Hello and thank you for using Planify, I could not reproduce the issue, probably your tasks were collapsed, you can see if you click on the arrow icon.


https://github.com/user-attachments/assets/0adb8c51-76b0-43e0-b7e2-1f0a6181fdbb

**Comment by yang-musa** [comment]
![Screenshot from 2024-09-12 11-06-22](https://github.com/user-attachments/assets/b32afd85-c970-4153-925d-76d64b59e31d)

I have expanded the task and I still don't see the subtasks. See attached screenshot. You can see in the left column that the project "RWC HE Parking" has 4 tasks, but when you look at the task list on the right you will see that there is only one task *expanded* with no subtasks listed below.

**Comment by yang-musa** [comment]
![Screenshot from 2024-09-12 11-09-05](https://github.com/user-attachments/assets/6d23c8c7-664f-4615-a77d-12c64e246590)

Now I added a new dummy task and the whole list of subtasks becomes visible. See screenshot. (Sorry they're all dummy tasks, I had completed all the original subtasks ;-) )

**Comment by yang-musa** [comment]
Also, I don't see the arrow (chevron? Caret?) on the left to expand the task, as in your example. I have an arrow on the right, as seen in the screenshots. As mentioned previously, I'm using Planify 4.11.0 from Flathub. Assume that's the latest? Is it because I'm using Fedora Gnome and you're using something else?

**Comment by golamrabbiazad** [comment]
https://github.com/alainm23/planify/issues/1428#issuecomment-2346936386

https://github.com/alainm23/planify/issues/1428#issuecomment-2346936386

> Also, I don't see the arrow (chevron? Caret?) on the left to expand the task, as in your example. I have an arrow on the right, as seen in the screenshots. As mentioned previously, I'm using Planify 4.11.0 from Flathub. Assume that's the latest? Is it because I'm using Fedora Gnome and you're using something else?

It might happen because of GNOME or old version cache.

To Reproduce
Steps to reproduce the behavior:

1. Create a Project
2. Add a task and name it  "A"
3. Add two subtasks, and give task titles to "B" and "C" under "A" Task.
4. Collapse task "A".
5. Expand task "A", it will open the markdown view, and all the subtasks under "A" tasks are hidden as well as the task's left chevron icon.

Screenshot
[Screencast from 2024-09-14 12-34-50.webm](https://github.com/user-attachments/assets/96fee35b-accf-4b0b-9347-321fa2edcd62)

What I have seen in the screenshot from you is that some icons are different than what I have. 

In your case chevron not showing at all. For me, the chevron showing but it is different than @alainm23

**Comment by alainm23** [comment]
Hi @golamrabbiazad It is correct, the chevron icon is hidden when viewing the detail of a task, I have to find where to place it, because in that state there is no way to see the sub tasks.

**Comment by alainm23** [comment]
Add this button to view the subtasks when the parent task is open.I also added some missing icons to the gresources.
https://github.com/user-attachments/assets/e577541a-527b-4001-8467-e54655969e41

**Comment by yang-musa** [comment]
Thanks for a great app and the quick fix!
