### ISSUE TITLE
Mute notification sound on expanding tasks

### ISSUE THREAD

**Issue by Andrewsudarikov** [alainm23/planify#180]
**Describe the solution you'd like**
Add an option to mute notification sound when expanding a task to view its notes and checklist.

**Additional context**
It may be distracting to users, especially if involved in constant editing and operations with multiple projects/tasks/checklists.

**Comment by 4jNsY6fCVqZv** [comment]
This is an exciting issue!
I haven't figured out the rule yet when this sound is played. For example, I currently have a project with several sections, where only in the first section four tasks are created. At first I thought it was due to whether a note was created in the task.
However, only one of two tasks with a note has this sound.
Also, the sound reminds me of a system sound in elementary, which indicates an error. For example, if I press the back key more often than there are characters.

There are three questions for me in this issue:
1. What function does sound perform at that point and according to what rules does it work?
2. How can I turn it off if I want to?
3. If it needs sound at this point, why this one? I find it irritating/unsuitable.

**Comment by alainm23** [comment]
Thank you for your comment. Sound is not a behavior programmed by Planner, rather a default behavior in elementary OS that indicates an error and a warning. You can disable it in system settings > Sounds

**Comment by Andrewsudarikov** [comment]
But it means the user should disable all error notification sounds. Maybe something could be done to prevent this sound fro occurring?

**Comment by alainm23** [comment]
What kind of language do you use on your system? I use Spanish and I had the problems when I use special characters for example 'ñ'

**Comment by 4jNsY6fCVqZv** [comment]
> rather a default behavior in elementary OS that indicates an error and a warning.

Indeed, in my case the trigger seems to be a special character in a section title.
But I don't understand: Why would a task or section with a special character trigger such a system alarm/system warning? And this only happens when the note element is opened or closed.

**Comment by alainm23** [comment]
This happens because when you activate the editing of a project, section or task Planner automatically gives the focus to the Gtk.Entry and sends the cursor to the last character so you can edit quickly. But it seems that special characters do not take them into account and send an error.

**Comment by 4jNsY6fCVqZv** [comment]
>  But it seems that special characters do not take them into account and send an error.

And how exactly does this cause the error sound?

**Comment by 4jNsY6fCVqZv** [comment]
By the way, it does not make the sound with every action.

**Comment by 4jNsY6fCVqZv** [comment]
@alainm23 How did you solve it?

**Comment by alainm23** [comment]
E solved the problem for the moment by selecting the whole task to start editing quickly.

![image](https://user-images.githubusercontent.com/33765137/73947186-14074780-48c5-11ea-9bd3-83ec943fb25d.png)

**Comment by 4jNsY6fCVqZv** [comment]
Thanks! Does it also make sense to create a superordinate issue for this problem in the GTK issue tracker? https://gitlab.gnome.org/GNOME/gtk/issues/

**Comment by alainm23** [comment]
I think I know what the problem is and it's not a Gtk mistake, I just have to think of a better way to do it. But thank you very much.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for continuing to look for a good solution!

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for continually looking for a sustainable solution! And for the first step towards an improvement.
