### ISSUE TITLE
Tasks marked for next week show up on the "Today" list, and tasks for today are not showing up.

### ISSUE THREAD

**Issue by wout** [alainm23/planify#253]
**Describe the bug**
I have a number of tasks in the Today list that are due next week. After reassigning the same due date, they disappear. The Upcoming list does show them at the correct day, so it is only in the Today section.

Also, and probably not unrelated, the badge for today shows 12 items, while there are only 6 items and there should be 3. Oddly, I have 3 tasks for today, but these are not shown in Today, only in the Upcoming section.

**UPDATE**
In the Upcoming section, 27/02/2020 is marked as Tomorrow, while we are the 27th today.

**To Reproduce**
1. No idea how they came there in the first place.

**Expected behavior**
Only overdue tasks or tasks due today should show up in the today panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/107324/75435782-73e49180-594b-11ea-8a62-7ad9d2fb67ea.png)

![image](https://user-images.githubusercontent.com/107324/75436782-00438400-594d-11ea-9a56-dc8c6190dc2d.png)

![image](https://user-images.githubusercontent.com/107324/75436948-54e6ff00-594d-11ea-9c81-67bca93e65b0.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/107324/75436158-008f4f80-594c-11ea-9aa6-6d3ce49f5531.png)

**Additional context**
These tasks are all on Todoist.

**Comment by 4jNsY6fCVqZv** [comment]
Took the time to do a local test. So no Todoist tasks. The used version is Planner 2.2.8 from the AppCenter.

**Scenario**

Three tasks 1,2 & 3.
Task 1 is scheduled for next week.
Task 2 is scheduled for today.
Task 3 is scheduled for tomorrow.

Task 3 is listed in the Inbox and also appears in the Upcoming view.

The Today view shows a neutral badge 1 and a red badge 1, but only task 2 is listed in the view. The red badge is excitingly related to the task that is scheduled for a week from now (task 1). The neutral badge refers to the task which is scheduled to be completed today (task 2).

I would expect that only tasks that are current for today are displayed here (task 2).
But I wonder what should happen to overdue tasks? Does it make sense to introduce an extra view for this?

The Dock shows badges for two tasks for today. Correctly, only task 2 should be listed.

**Two observations**

1. One thing I notice is that the Upcoming View has no counter/badge at all. Is this intentional or would a counter/badge make sense here as well?

2. The coloring also irritates me. A task that is due for today is set high in priority. That seems understandable to me.
In the Inbox view the task for today gets only a yellow label, because the icon for Today is yellow, while the icon for the Upcoming view with the probably lower priority tasks in it gets the red signal color. In the Inbox view, however, the farthest away task is marked with a red label. Somehow I think the other way around would be more consistent.

**Comment by wout** [comment]
Small update here. After restarting the app, today shows all dated tasks from today onward. And there are indeed 12. So the badge is updated while staying open overnight, but the list is not. Related: #240

**Comment by alainm23** [comment]
What ugly bug, I'm sorry for being so clumsy. I just solved it. I ran some tests and I think everything's fine. If you could build Planner from the repository and test if this was solved I would be very grateful.

https://github.com/alainm23/planner#building

**Comment by 4jNsY6fCVqZv** [comment]
That surprises me a little.
Since the bug report, there hasn't been a commit to the code, has there? Then how did you solve it?

**Comment by alainm23** [comment]
@4jNsY6fCVqZv  😅️
