### ISSUE TITLE
Some design suggestions.

### ISSUE THREAD

**Issue by harisvsulaiman** [alainm23/planify#3]
I know that this is not finalized, but here are some suggestions.

* Isn't it better if this is a dialog? 
![image](https://user-images.githubusercontent.com/29329325/48054251-d522a780-e1d2-11e8-82ac-dfc389b2ff2d.png)
So that the windows are separated from the main window, and multiple add item dialogs can be opened at once.

* Vertical split for a subtask is better since this UI confused me and some other people I showed it to.
![image](https://user-images.githubusercontent.com/29329325/48054438-46625a80-e1d3-11e8-80a9-b57d6afad247.png)

* I believe the task detail should also be opened in a new window or inside the current window in full mode.
![image](https://user-images.githubusercontent.com/29329325/48054561-993c1200-e1d3-11e8-9f67-047865de3e89.png)

**Comment by alainm23** [comment]
Thanks for your comments, the feedback is always good.

- If I thought about using a dialog, but decided not to do it since adding more windows to the interface makes it messy, to solve the task aggregation at the same time, I am adding different shortcuts to make the creation process faster.

- Here is a good point, I also thought that the horizontal orientation was confusing, I will change it to vertical.

- The same answer to the first, open many dialog saturates the interface, and if I do full screen could not work with two tasks at the same time, if you opened many tasks and you want to close all at the same time, double click on any part of the interface
