### ISSUE TITLE
(Deliberately) Clicking outside a project title, a note or a task title does not cause the respective action to be saved and closed in its current state

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#310]
Same goes for area and section titles.
It's especially obvious in the notes field. The mouse pointer keeps blinking. Neither with ESC nor with a click outside the text field, I can remove the focus again.
My first question: Have you consciously designed it this way and not differently?
And second question: Do you think that you could somehow make the handling smoother?

**Comment by alainm23** [comment]
I'm sorry, I don't understand the problem.

**Comment by 4jNsY6fCVqZv** [comment]
What exactly do you not understand about my problem description?
Or the other way round: Is there something that you understand?

**Comment by alainm23** [comment]
I remember developing this feature but removing it for the following reasons or problems:
The most correct way to do this is using this [event](https://valadoc.org/gtk+-3.0/Gtk.Widget.focus_out_event.html).
- When I edit an area, section or project name I sometimes want to add an emoji, when the Emoji Popover opens it causes the edit to finish because the entry lost focust.
![focus_out](https://user-images.githubusercontent.com/33765137/79778794-f1e76800-82fe-11ea-86a7-44ebc80fc63e.gif)
- The same behavior if I want to copy some text.

**Comment by alainm23** [comment]
I will close this issue for the reasons mentioned above.
