### ISSUE TITLE
Today view does not show all tasks for today

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [alainm23/planify#333]
The bagde in the dock and in the sidebar each show the correct value 4, the badge count settings are set to "Today".
The tasks are distributed like this:Three tasks from a project x plus one task from the inbox marked "Today". The task from the inbox is counted and the second task from project x, while two other tasks from the project are ignored. Restarting the app does not help either.

How can this be solved?
The Planner version is 2.3.3 from the AppCenter.

**Comment by ffshr** [comment]
Same problem here, running elementary planner 2.3.2 from Flathub. In my case next to Today it shows correctly the number 2 of overdue tasks and 6 of due tasks for today, but actually displays in the right-hand pane only 3. When marking some of them as done, they disappear but no new ones show up.

**Comment by Julioevm** [comment]
I have the same issue with 2.3.2
This is a task that was set due to tomorrow yesterday, but today its not appearing in the today category:

![image](https://user-images.githubusercontent.com/38758281/80569850-065fea80-89fa-11ea-8370-34bc043b5659.png)
Yet today is empty:
![image](https://user-images.githubusercontent.com/38758281/80569881-17a8f700-89fa-11ea-88e9-270bf6f196b8.png)

**Comment by Julioevm** [comment]
It keeps happening, it seems task that were planned for x day don't load in the today section when the day arrives.

**Comment by alainm23** [comment]
Fixed, wait the update please.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks a lot! Looks to me like it's all working out now.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you, it seems to be working now!
