### ISSUE TITLE
Automatically cancel new empty tasks

### ISSUE THREAD

**Issue by raproenca** [alainm23/planify#370]
Not sure whether I should file this under bug report or feature request, but I believe it is a bug.

**Describe the bug**
When I am adding a new task and decide to not enter the task title and click away from the empty task, it should automatically cancel/delete the empty task - not require me to explicitly click the "Cancel" button. With the day-to-day use it is easy to end up pilling several "empty tasks" in your projects/sections this way.

**To Reproduce**
1. Click the "+" button to add a new task;
2. Type in the task name and hit enter;
3. Don't add any more tasks because you only wanted to add one;
4. Click away, into another task, project, or anywhere really;
5. The "empty" task still where you left it, requiring you to explicitly click "Cancel"

**Expected behavior**
When you don't enter any information into a new task (like the actual name of the task), and click away, the task should be cancelled automatically - as if you clicked the "Cancel" button, but without to actually requiring you to click cancel.

**Screenshots**
See the several "emtpy tasks" pilling up:
![planner-emtpytasks](https://user-images.githubusercontent.com/23019356/82068547-83e95300-96a8-11ea-891e-ad77eace4ec0.gif)

**Desktop (please complete the following information):**
 - OS or DE: gnome 3.36
 - Version 2.3.5 (flathub)

**Additional context**
This is the expected behaviour of every good task manager I used so far. Planner is close to the best one I used, so I expect it to behave like that too =)

**Comment by 4jNsY6fCVqZv** [comment]
When I read your issue, the following wish comes up in me: When I create a new task, I'd rather edit it directly than have another task automatically created for me, which I usually just have to click away.
I also find it more irritating than helpful if several empty tasks are displayed at the same time. It would help me a lot if only the current task has the focus and the others are not shown at all, because empty tasks should not be saved from my perspective.

**Comment by 4jNsY6fCVqZv** [comment]
Your issue expresses for me what has occupied my workflow with Planner for a long time.

When I create a new task, I prefer to be able to edit it directly.
I don't want to have tasks created automatically, but I want to consciously decide for myself whether another task should be added.
Currently it is so that a new task is always automatically created for me. Usually I have to click this one away.

It would support my workflow if only the current (new) task is always open and in focus. Several empty untitled tasks that are displayed open (like mentioned above) make my screen very cluttered and distract my workflow, because I want to take care of all the unintended and empty placeholder tasks first. That means I need to cancel them somehow.

How about when empty tasks are simply no longer saved and therefore no longer displayed?

I would be interested to know what the motivation of the current implementation is. So that I can understand things better and that we can more easily discuss improvements afterwards.  @alainm23
