### ISSUE TITLE
Design - 0

### ISSUE THREAD

**Issue by ILope92** [alainm23/planify#4]
As I liked the old version of the project, it was very convenient.

![image](https://user-images.githubusercontent.com/31201817/48316245-20352400-e5f2-11e8-9f6a-6099673c0ae5.png)

Where is this interface now?!

**Comment by alainm23** [comment]
The first version of Planner was good, you can create projects, to-do list. The problem is that the interface does not adapt to the new functions it proposed to include. So I decided to redesign it, but do not worry, many of the functions of the first version of Planner will be available. quiet everything is for good
