### ISSUE TITLE
Use native gtk window decorator

### ISSUE THREAD

**Issue by stefabat** [alainm23/planify#401]
Hi,

Would it be possible to allow the user to select the native GTK window decoration?
Don't get me wrong, the style of the app is undoubtedly beautiful by itself and within elementary OS, however, when used in any other distro with (probably) GNOME, the app feels a bit out of place.

**Comment by alainm23** [comment]
We discussed a lot about this approach since the beginning of the project and we decided to enforce the elementary OS theme for many reasons.
The most obvious are:

- Ability to fully control the UI and UX of the application on every platform.
- Offer a consistent user experience to everyone.
- Remove the burden of supporting a million different DEs and Themes.
- Keep the focus on the architecture instead of spending time fixing themes issues.
