### ISSUE TITLE
Ampersand character disappears in checklist

### ISSUE THREAD

**Issue by rzelnik** [alainm23/planify#445]
**Describe the bug**
When I type ampersand (&) character in the checklist, it disappears after task submitting.

**To Reproduce**
1. Create a task
2. Click on Add Checklist
3. Type "Tom & Jerry" in the checklist's subtask
4. Click Enter
5. See "Tom  Jerry"

**Expected behavior**
The & character should remain visible.

**Screenshots**
I will create screenshots when necessary.

**Desktop (please complete the following information):**
 - Ubuntu 20.04 LTS
 - Planner Version 2.4.5

**Comment by BeatLink** [comment]
I do recall seeing something that intentionally does this while i was poking around in the codebase in the past but you'd have to ask the app author to confirm. Usually its for validation reasons because certain characters are not allowed in certain places. If this cant be fixed, would a better alternative be to convert all '&' to 'and'?

**Comment by alainm23** [comment]
Yes, for some reason the Todoist API does not process the '&' character correctly.

**Comment by alainm23** [comment]
Duplicate #234

**Comment by BeatLink** [comment]
Ahh so this can be closed then
