### ISSUE TITLE
Link GitHub repo in homepage

### ISSUE THREAD

**Issue by rixx** [alainm23/planify#485]
I found out about Planner (the most polished and pleasant to use Linux desktop application I've encountered in a long time) via the [homepage](https://planner-todo.web.app/). But finding this repo to figure out alternate installation methods took me a long time (via flatpak, and their config repo, and the sources list in there). It would be nice to have a direct link from the homepage here.

**Comment by Adda0** [comment]
I can only agree. I was surprised I couldn't find a link to this repo on the homepage too when I found out about Planner some time ago. Of course, this is not of much importance, but it would be nice to have when considered Planner a Linux application where people are often used to look up for GitHub repository rather than other websites when they install new applications.
