### ISSUE TITLE
Add ability to change planner database location from command line

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#518]
- [ ] Add ability to reset planner database location to default from command line
- [ ] Add ability to set planner database file path from command line

**Comment by alainm23** [comment]
Thank you very much for your comment, I will have to reject this request for the following reason.
- Moving only the location of the database file will not make your projects sync correctly, there are still other variables that need to be synced stored in dconf.
- In order to synchronize between devices I am creating an import / export function

**Comment by BeatLink** [comment]
Ahh okay fair enough
