### ISSUE TITLE
Errors during build

### ISSUE THREAD

**Issue by ejiix7** [alainm23/planify#562]
**Describe the bug**
Errors during build.

**To Reproduce**
```
$ git clone https://github.com/alainm23/planner.git
$ cd planner
$ meson build --prefix=/usr
$ cd build
$ ninja
```

**Output**
```
../src/Services/Tasks/Store.vala:522.27-522.30: error: Argument 1: Cannot convert from `unowned GLib.SList<ECal.ComponentId?>' to `unowned GLib.SList<weak ECal.ComponentId?>'
        on_tasks_removed (cids);
                          ^^^^
../src/Widgets/SourceRow.vala:190.9-196.9: warning: unhandled error `GLib.Error'
../src/Widgets/TaskRow.vala:424.13-424.95: error: Invalid assignment from owned expression to unowned variable
            remove_prop = ical_task.get_first_property (ICal.PropertyKind.DESCRIPTION_PROPERTY);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Additional Info**
OS - Arch Linux

**Comment by alainm23** [comment]
I have been doing some tests for CalDAV support, it is probably due to a version of a library, these are the ones I use at the moment. This is solved when Planner is distributed only from Flatpak

![image](https://user-images.githubusercontent.com/33765137/95874808-ebc6c700-0d36-11eb-8971-54977181e453.png)

**Comment by ejiix7** [comment]
Thanks. Indeed, the problem is with a more recent version of library. Flatpak planner version works fine.
