### ISSUE TITLE
No export option available

### ISSUE THREAD

**Issue by yadox666** [alainm23/planify#590]
I was reading extensively many websites about Planner and I noticed there should be an export option in Preferences - General - Export and there isn't any. It's important because of making backups of introduced data in order to secure all the data. Also there's an import option in the home tab.

**Comment by nsg** [comment]
![Screenshot from 2020-10-30 14-13-20](https://user-images.githubusercontent.com/16388/97709104-198f6800-1aba-11eb-85a4-6f11ea6e448c.png)

Are you using the latest version? I think the export option was introduced in 2.5.

**Comment by Leon0402** [comment]
@nsg Such an option doesn't exist for me either (Using the latest version)

There is an "backups" settings though (so not in general, but as it's own setting), but you can't use it. Nothing happens, when you click on it: 

![image](https://user-images.githubusercontent.com/33933142/97777951-ec9f8b80-1b73-11eb-86d1-d5908509c4d0.png)

See #593

**Comment by itormint** [comment]
Same problem here: no "Export database" option under Preferences > General like @nsg screenshot. Also I can not see that "Backups" option shown by @Leon0402 
I am using version 2.5.7, installed via pop!_os app shop.

**Comment by itormint** [comment]
I don't know if the option is working or not but master version has the button "drawing" call commented:
https://github.com/alainm23/planner/blob/eae7508b0d75d9efc659e55bf3a88c5360a29a5e/src/Dialogs/Preferences/Preferences.vala#L870
Seems like it was changed alongside this fix: https://github.com/alainm23/planner/issues/469

**Comment by itormint** [comment]
I built it and removed some comments and the export/import seems like working (not tested much). Also, I guess this may be probably breaking something else and that's why it was commented but no clue tbh.
Lines uncommented:
https://github.com/alainm23/planner/blob/eae7508b0d75d9efc659e55bf3a88c5360a29a5e/src/Dialogs/Preferences/Preferences.vala#L870
https://github.com/alainm23/planner/blob/eae7508b0d75d9efc659e55bf3a88c5360a29a5e/src/Dialogs/Preferences/Preferences.vala#L897
https://github.com/alainm23/planner/blob/eae7508b0d75d9efc659e55bf3a88c5360a29a5e/src/Dialogs/Preferences/Preferences.vala#L928
