### ISSUE TITLE
Completing a recurring task with time does not preserve the time

### ISSUE THREAD

**Issue by BeatLink** [alainm23/planify#597]
**Describe the bug**
When a recurring task with a time is completed, the time is cleared while the date is updated.

**To Reproduce**
1. Create a Task
2. Enable recurrence on the task
3. Set a time on the task
4. Click the check mark to complete the task
5. Notice that the task will  be updated to the new date but the time data will be erased

**Expected behavior**
The app should keep the time setting after being updated to the new recurrence date

**Screenshots**
Before Completing: 
![image](https://user-images.githubusercontent.com/47278150/97807905-811bf380-1c31-11eb-92d4-767eb8a1fb2d.png)

After Completing (notice the 18:00 is gone)
![image](https://user-images.githubusercontent.com/47278150/97807920-8e38e280-1c31-11eb-8a36-9a98f9bbb57d.png)

**Desktop (please complete the following information):**
 - OS or DE: Linux Mint Cinnamon 20
 - Version 2.5.7

**Additional context**

**Comment by gunalabs** [comment]
So actually it preserves the time.
After doing all this, and When I go and see the Schedule, the time is turned on and its saved.
But after checking once, its not displaying.
**When I turnoff the time and turn on, its showing**
So the issue seems a simple display updation problem.
Its there but not displayed. Only if we trigger again, its displayed.
