### ISSUE TITLE
Feature Request: Add on top of "Task Type" a "Note Type" for notes

### ISSUE THREAD

**Issue by levipmartin** [alainm23/planify#660]
Sometimes you have tasks and you want to refer to some info.
The suggestion is to add another type on top of the currently implementet task type, such that you can add notes to a project which just stay there, don't have a priority or can be "done" just a textfield for information, this can be extended later to support images and more.
Another interesting optimization in the same context would be the option to "link" from tasks to notes such that you can build some sort of hirachy below a note and create tasks that refer to a certain note.

**Comment by joeysbytes** [comment]
I would also vote for this. I think all we need is a way to disable the completion checkbox on the "note" type, cause it's really annoying when I accidentally click this and the note disappears. As a work-around I made a "Notes" project and "notes" label for these, and it works well.

**Comment by Riksu9000** [comment]
You can add a note to a project to store relevant information. Each task can have a description and even attachments. It looks like sections can also have descriptions, but they are only visible in the board view. Can you describe your situation where these features fall short?

**Comment by joeysbytes** [comment]
I am thinking sticky-note (short, small) sized information, that are not necessarily related to specific projects or tasks. These would be reference notes. As random made-up examples:

- How to add color to my bash scripts
- How to update the DNS records and restart the service
- Magic LibreOffice Calc formula to do this complicated thing

I can do this in Planify now. What I want is the ability to NOT be able to close them like a task, because I accidentally do this more than you think, especially on a laptop with a touchpad.

Hope this makes sense / clarifies my ask.

**Comment by joeysbytes** [comment]
I also want to add that I do not want to over-ride what @levipmartin asked for above, he definitely has some good ideas there. But maybe what I am asking for could be a good first step?

**Comment by Riksu9000** [comment]
Thanks for the clarification. I personally use planify for things that need processing, such as tasks, but also random notes. I will check them later and decide what I'll do with them, similar to the GTD system https://hamberg.no/gtd/. I've been using Folio for notes that I keep for reference.

**Comment by alainm23** [comment]
Could this be a solution?

![image](https://github.com/alainm23/planify/assets/33765137/c154d224-df17-4bca-95e3-7bc02159a29d)

**Comment by joeysbytes** [comment]
That looks like an extremely simple, and brilliant, solution! Can't wait to try it!
