### ISSUE TITLE
New window can't be resized 

### ISSUE THREAD

**Issue by isshin1** [alainm23/planify#719]
**Describe the bug**
On opening a project in new window, it acquires full screen and can't be resized at all. In gnome-shell, resizing using mouse from border has no effect. On sway, resizing sometimes result in window transitioning to another place but no change in size here as well

**To Reproduce**
1. Go to any project
2. Click on `open new window
3. try to resize new window using mouse 
4. no effect on window size

**Expected behavior**
new window should get resized to desired size

**Desktop (please complete the following information):**
 - OS or DE: [gnome]
 - Version [3.38.3]

Edit : maybe its because of titlebar ? If i uncomment both these [lines](https://github.com/alainm23/planner/blob/35cc1a2ad63b47523990af3e3d67cf4031f52ad8/src/MainWindow.vala#L55) defining size of new widget, titlebar is enabled and window have default size as defined. Also it is resizable easily

**Comment by ChibiYuzu** [comment]
Hi there!
I have the same issue. I'm using Ubuntu 20.04 and Planner version 2.7 (haven't seen new updates, if there is one). I originally downloaded it from the Ubuntu Software snap store. I see that you closed the issue, but it seems like it hasn't been resolved since April. At least, I'm encountering it and it's been quite recent (for the last 10 days). Do you have any advice to solve this? Thank you!
