### ISSUE TITLE
Please Ubuntu version 😭

### ISSUE THREAD

**Issue by papac** [alainm23/planify#827]
Please Ubuntu version 😭

**Comment by 12people** [comment]
@papac You can get Planner on Ubuntu by via Flatpak.

To do so, simply install Flatpak using the Terminal according to these instructions: https://flatpak.org/setup/Ubuntu/

And then install Planner from Flathub: https://flathub.org/apps/details/com.github.alainm23.planner

**Comment by toasterrepairman** [comment]
It's also quite trivial to compile it for yourself, since there aren't very frequent breaking changes. You can automate it on platforms like Arch, but with Ubuntu you'll need to roll up your sleeves a bit and grab a few dependencies. Once you have a binary though, you can run it on any of your Ubuntu-based systems.
