### ISSUE TITLE
CalDAV Support does not work properly

### ISSUE THREAD

**Issue by ghost** [alainm23/planify#897]
Hi,

First of all: Thank you very much for this beautiful app. I was looking forward for the CalDAV option. I just tried it out and have an issue. I am able to connect the CalDAV-account with Planner. Unfortunately, Planner says there are no Tasklists available in the online-account. On the other hand, when i click on "create a tasklist" in Planner, a new tasklist appears in the online-account,  but does still not appear in the app itself.

I use Ubuntu and my CalDAV-Account ist related to a infomaniak e-mail-adress. Before that, i used nextcloud and i think infomaniak is pretty much a copy of nexcloud (at least the calendar and tasks-function). I don't know if this description is very helpful...

Kind regards

**Comment by ebousse** [comment]
I have a few problems with CalDAV as well:

- I have a Nextcloud CalDAV account configured through "GNOME Online Accounts", which appear in my list in Planner. However when trying to create task there, here is the result:
![image](https://user-images.githubusercontent.com/5868014/165709639-53f68e16-6998-4de0-a867-a75029e751ef.png)

- I find it almost impossible to add a new CalDAV account manually in Planner, as each time I click outside the Settings window, or more generally each time I change the focus outside the Settings window, then it disappears and I have to start over the configuration of my account. As I need to copy and paste my credentials, this is quite problematic.

**Comment by therealrobster** [comment]
I just want to follow up and say I basically can not enter a new caldav account manually as stated by @ebousse.  The settings window closes every time I click out and with URL's and passwords to manage it is more than cumbersome.  I do love this app, but wanted to report some feedback to help also.

**Comment by mkikets99** [comment]
May I join?...
I have the weird thing...
So it works with sending info but not receiving...

If i hit `+` on CalDAV instance, it is creating new list on self-hosted server, but it not receiving back info about success... or it may be that it reading it with errors.

**Comment by ebousse** [comment]
Just to share one observation: as said in my previous comment https://github.com/alainm23/planner/issues/897#issuecomment-1111893458 I found a case where Planner does successfully work with CalDAV accounts on my system… but only if said CalDAV accounts were are "part" of a configured GNOME Online Account. For instance, I have several "Nextcloud" accounts in GNOME Online Accounts, and they successfully appear and work properly in Planner. _Note that for some reason, I can now succesfully create new tasks in such accounts using Planner, contrary to what I said in as said in my previous comment https://github.com/alainm23/planner/issues/897#issuecomment-1111893458._

I suppose the reason is that, in this scenario, Planner does not have to speak CalDAV directly, but only has to speak to the GNOME evolution data server, which itself must be in charge of speaking CalDAV with each Nextcloud account (in my case).

Luckily, it appears GNOME will soon have support for CalDAV accounts directly in GNOME Online Accounts (see [this MR](https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/merge_requests/98)). I wonder if this will coincidentally allow me to finally use Planner for (non-Nextcloud) CalDAV accounts! Stay tuned…

**Comment by vepain** [comment]
Hi everyone,

Even if as @ebousse I can add a new task to an already existing task list, I can't create a new task list nor change the colour of an existing task list (see #943).

In all the cases, I have a permission denied error (missing password or something related).

This behaviour in Ubuntu appears for google account, NextCloud and CalDAV account configured directly into Planner.
In other applications (thunderbird etc.), these configurations work correctly.

All these errors can be related to Planner which may not handle CalDAV protocol correctly.

**Comment by ebousse** [comment]
Quick follow-up: most my problems seem to have disappeared when trying today version 3.0.10 of Planner. I can add a CalDAV account without problem, and add/remove tasks. I do still encounter crashes here and there, but I haven't yet identified the exact cause, and overall everything kinda seems to work.

**Comment by Cris70** [comment]
I have planner 3.0.10 installed (flatpak) on openSuse Tumbleweed. 
When I try to connect to a Nextcloud Tasks calendar, all I get is a red box which reads "Could not save configuration".

**Comment by alainm23** [comment]
CalDAV support is under development for Planify, I will close this issue until the implementation is done. thank you.
