### ISSUE TITLE
Problem adding records

### ISSUE THREAD

**Issue by ricardsos** [alainm23/planify#934]
When I sync with my Todoist account I add projects but the Linux application does not show them and they appear in the web application.

**Comment by JiveyGuy** [comment]
How did you sync with todoist I can't find the option

**Comment by adriandelgg** [comment]
I'm having the same problem. The application is broken and unusable.

**Comment by JiveyGuy** [comment]
> I'm having the same problem. The application is broken and unusable.

I don't want to discourage the developers as they offer a great free planner but due to a long list of issues I have left this application as my main planner, I recommend habitica as a good replacement, it runs in the browser or as an android app. 


This issue is so major and possibly destructive to hours of work on your local machine that it defeats the purpose of a planner, optimizing time. This turns the app into a time waster.

**Comment by adriandelgg** [comment]
Same. I started using Todoist from Snap on Linux. Planner was basically Todoist anyways.

**Comment by alainm23** [comment]
Fixed in the new version of Task Planner
