### ISSUE TITLE
planner seems to have magically deleted all my tasks.

### ISSUE THREAD

**Issue by paulavmf** [alainm23/planify#964]
Today a open my planner and I can't see any task right now..
Projects, Labels and sections are still there but no tasks
any clue?

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - planner  version 3.0.10

**Comment by will-ca** [comment]
There's an SQLite database at `~.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner/database.db` for Flatpaks, or its non-Flatpak equivalent for native builds (presumably somewhere in `~/.local/share/`). See if it's empty.  Don't run Planner since it'll probably overwrite it. (Too late for that, I guess.) Hope you have backups. Try to fix it if it's broken. (IMO [DB Browser for SQLite](https://sqlitebrowser.org/) is the most convenient, though of course use what you like.) Question why a database capable of catastrophic failure, as opposed to plain text files, was even chosen in the first place for a note-taking app.

Compare: #957

**Comment by paulavmf** [comment]
I cant finde any database... in my system I find planner here:

/var/lib/flatpak/app/com.github.alainm23.planner
/var/lib/flatpak/repo/refs/remotes/flathub/app/com.github.alainm23.planner
/var/lib/flatpak/repo/refs/heads/deploy/app/com.github.alainm23.planner

I guess data/ should be inside the first option but I cant finde any data folder named data... 
Anyways.. I already open planner so.. data is rewrited... It is a pitty becouse I was finding planner very usefull..

Thank you anyways

**Comment by will-ca** [comment]
@paulavmf That's where Planner is installed. You want to look in your home directory for user data. "`~`" means user home on Linux.

So: `/home/YourUsernameHere/.var/app/com.github.alainm23.planner/data/com.github.alainm23.planner/database.db`.

Turn on "Show Hidden" for your file browser too for `.var`.

Your data may not be overwritten. There is precedent before that sometimes data is accidentally hidden because of a bug, and then an update brings it back (https://github.com/alainm23/planner/issues/893#issuecomment-1107472266). The fact that categories are still shown is a sign that it's not completely overwritten. I just meant it's safer to not launch it just in case.

**Comment by paulavmf** [comment]
found it! thank you.. but I dont see losts tasks.... I should see all tasks in table Items, isn't???
Before I realised all tasks were deleted I wrote some new ones.... then I guess that re-wrote everything...

**Comment by alainm23** [comment]
Fixed in [planner-gnome](https://github.com/alainm23/planner/tree/planner-gnome) branch
